version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
    - ./public:/usr/lichen/public

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=postgres
