version: '3.2'
services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - 9000:9000
    volumes:
      - ./public:/usr/lichen/public
    environment:
      - NODE_ENV=development

  web:
    container_name: web
    restart: always
    build: ../lichen-web
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=development

  # reverse-proxy: 
  #   build: ./infra/reverse-proxy/
  #   container_name: reverse-proxy
  #   restart: unless-stopped
  #   ports: 
  #     - 8085:80
  #     - 8086:443
  #   depends_on:
  #     - api
  #     - web
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - './letsencrypt:/letsencrypt'
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=postgres
